Commeted out Z-limit switches in fix-attempt for:
Traceback (most recent call last):
  File "prusa-i3.py", line 88, in <module>
    hardware.setup_hardware(thread='servo-thread')
  File "/home/machinekit/Prusa_i3-CRAMPS/cramps.py", line 77, in setup_hardware
    hal.Pin('bb_gpio.p9.in-13').link('limit-2-home')   # Z
  File "hal_pin.pyx", line 105, in machinekit.hal._Pin.link (hal/cython/machinekit/hal.c:4311)
  File "hal_net.pyx", line 94, in machinekit.hal.net (hal/cython/machinekit/hal.c:21260)
TypeError: net: signal 'limit-2-home' can not add writer pin 'bb_gpio.p9.in-13', it already has HAL_OUT pin 'gantry.2.home